# Generated by Django 5.2.3 on 2025-06-27 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_name_en_category_name_remove_category_name_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
