# Generated by Django 5.2.3 on 2025-06-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='desc',
        ),
        migrations.AddField(
            model_name='product',
            name='desc_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='desc_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='desc_uz',
            field=models.TextField(blank=True),
        ),
    ]
