# Generated by Django 5.2.3 on 2025-06-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_product_desc_product_desc_en_product_desc_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='big_img',
            field=models.ImageField(blank=True, upload_to='products/big/'),
        ),
        migrations.AddField(
            model_name='product',
            name='desc_full_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='desc_full_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='desc_full_uz',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
