# Generated by Django 5.2.3 on 2025-06-29 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='last_name',
            new_name='surname',
        ),
    ]
