# Generated by Django 5.2.3 on 2025-06-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='big_img',
        ),
        migrations.RemoveField(
            model_name='product',
            name='desc_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='desc_full_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='desc_full_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='desc_full_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='desc_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='desc_uz',
        ),
        migrations.AddField(
            model_name='product',
            name='bigImg',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='category_slug',
            field=models.SlugField(blank=True, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='desc',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='product',
            name='descFull',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
