# Generated by Django 5.2.3 on 2025-06-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_product_big_img_remove_product_desc_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bigImg',
            field=models.ImageField(blank=True, upload_to='products/', verbose_name='большое фото'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, upload_to='products/', verbose_name='мини-фото'),
        ),
    ]
