# Generated by Django 5.2.3 on 2025-06-30 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_category_slug_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='main.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_slug',
            field=models.SlugField(blank=True),
        ),
    ]
