# Generated by Django 5.2.3 on 2025-06-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_product_category_alter_product_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='product',
            name='descFull',
        ),
        migrations.AddField(
            model_name='product',
            name='desc_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='desc_full_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='desc_full_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='desc_full_uz',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='desc_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='desc_uz',
            field=models.TextField(blank=True),
        ),
    ]
