# Generated by Django 5.2.3 on 2025-07-01 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bigImg',
        ),
        migrations.AddField(
            model_name='product',
            name='big_img',
            field=models.ImageField(blank=True, null=True, upload_to='product/big/', verbose_name='Большая картинка'),
        ),
    ]
