# Generated by Django 5.2.3 on 2025-07-01 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_product_bigimg_product_big_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id']},
        ),
    ]
