# Generated by Django 5.2.3 on 2025-07-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterField(
            model_name='product',
            name='big_img',
            field=models.ImageField(blank=True, null=True, upload_to='products/big/', verbose_name='Большая картинка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_slug',
            field=models.SlugField(blank=True, editable=False, verbose_name='Дублирующий slug категории'),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc_en',
            field=models.TextField(blank=True, verbose_name='Краткое описание (EN)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc_full_en',
            field=models.TextField(blank=True, verbose_name='Полное описание (EN)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc_full_ru',
            field=models.TextField(blank=True, verbose_name='Полное описание (RU)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc_full_uz',
            field=models.TextField(blank=True, verbose_name='Полное описание (UZ)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc_ru',
            field=models.TextField(blank=True, verbose_name='Краткое описание (RU)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc_uz',
            field=models.TextField(blank=True, verbose_name='Краткое описание (UZ)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Мини-фото'),
        ),
    ]
