# Generated by Django 5.2.3 on 2025-07-01 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_product_options_alter_product_big_img_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
