# Generated by Django 5.2.3 on 2025-07-02 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_order_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
