# Generated by Django 5.2.3 on 2025-07-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='img',
        ),
        migrations.AddField(
            model_name='news',
            name='banner_img',
            field=models.ImageField(default='defaults/no-banner.png', upload_to='news/banner/', verbose_name='Большая картинка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='thumb_img',
            field=models.ImageField(default='defaults/no-banner.png', upload_to='news/thumb/', verbose_name='Мини-картинка'),
            preserve_default=False,
        ),
    ]
