# Generated by Django 5.2.3 on 2025-07-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_remove_news_img_news_banner_img_news_thumb_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='banner_img',
        ),
        migrations.AddField(
            model_name='news',
            name='banner_bg',
            field=models.ImageField(blank=True, null=True, upload_to='news/banner/', verbose_name='Фон баннера'),
        ),
        migrations.AddField(
            model_name='news',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Если true — будет на баннере', verbose_name='Главная новость'),
        ),
        migrations.AddField(
            model_name='news',
            name='large_img',
            field=models.ImageField(blank=True, null=True, upload_to='news/large/', verbose_name='Большая картинка'),
        ),
        migrations.AddField(
            model_name='news',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='news',
            name='desc',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='thumb_img',
            field=models.ImageField(blank=True, null=True, upload_to='news/thumb/', verbose_name='Мини-картинка'),
        ),
    ]
