# Generated by Django 5.2.3 on 2025-07-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_remove_news_banner_img_news_banner_bg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='price',
        ),
        migrations.AlterField(
            model_name='news',
            name='banner_bg',
            field=models.ImageField(blank=True, null=True, upload_to='news/banners/', verbose_name='Фон баннера'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Если отмечено — эта новость пойдёт в баннер', verbose_name='Главная новость'),
        ),
        migrations.AlterField(
            model_name='news',
            name='thumb_img',
            field=models.ImageField(blank=True, null=True, upload_to='news/thumbs/', verbose_name='Мини-превью'),
        ),
    ]
