# Generated by Django 5.2.3 on 2025-07-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_remove_news_price_alter_news_banner_bg_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-is_featured', '-created_at'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.RemoveField(
            model_name='news',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='news',
            name='thumb_img',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title',
        ),
        migrations.AddField(
            model_name='news',
            name='desc_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание (EN)'),
        ),
        migrations.AddField(
            model_name='news',
            name='desc_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание (RU)'),
        ),
        migrations.AddField(
            model_name='news',
            name='desc_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Описание (UZ)'),
        ),
        migrations.AddField(
            model_name='news',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='news/thumbs/', verbose_name='Мини-картинка'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок (EN)'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок (RU)'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок (UZ)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='banner_bg',
            field=models.ImageField(blank=True, null=True, upload_to='news/banner/', verbose_name='Фон баннера'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Главная новость'),
        ),
        migrations.AlterField(
            model_name='news',
            name='large_img',
            field=models.ImageField(blank=True, null=True, upload_to='news/large/', verbose_name='Большое изображение'),
        ),
    ]
