# Generated by Django 5.2.3 on 2025-07-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_news_options_remove_news_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='banner_bg',
            field=models.ImageField(blank=True, null=True, upload_to='news/banners/', verbose_name='Фон баннера'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='news',
            name='desc_en',
            field=models.TextField(blank=True, default='', verbose_name='Описание (EN)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='desc_ru',
            field=models.TextField(blank=True, default='', verbose_name='Описание (RU)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='desc_uz',
            field=models.TextField(blank=True, default='', verbose_name='Описание (UZ)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='large_img',
            field=models.ImageField(blank=True, null=True, upload_to='news/large/', verbose_name='Большая картинка'),
        ),
        migrations.AlterField(
            model_name='news',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='news/thumbs/', verbose_name='Миниатюра'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Заголовок (EN)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_ru',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Заголовок (RU)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_uz',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Заголовок (UZ)'),
        ),
    ]
