# Generated by Django 5.2.3 on 2025-07-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_profile_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AddField(
            model_name='order',
            name='customer_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес клиента'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя клиента'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='Телефон клиента'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_surname',
            field=models.CharField(blank=True, max_length=100, verbose_name='Фамилия клиента'),
        ),
    ]
