# Generated by Django 5.2.3 on 2025-07-12 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_order_options_order_customer_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
